# Generated by Django 5.0.7 on 2024-08-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_rename_productm_order_product_and_more'),
    ]

    operations = [
        
    ]
