# Generated by Django 5.0.7 on 2024-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_address_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
