# Generated by Django 5.0.7 on 2024-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_rename_name_podcast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(upload_to='podcasts'),
        ),
    ]
